apiVersion: v1
kind: Service
metadata:
  name: podinfo-connect-web
  labels:
    zarf.dev/connect-name: podinfo-connect-web
  annotations:
    zarf.dev/connect-description: "Creates a web connection for zarf"
spec:
  selector:
    app.kubernetes.io/name: podinfo
  ports:
    - name: http
      port: 9898
      protocol: TCP
      targetPort: 9898